server:
  port: 9004

spring:
  application:
    name: ktc-article                                                 # 指定服務名
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss                                  # 格式化日期字符串
    time-zone: GMT+8                                                  # 格林尼治標準東八區時間
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.205:3306/ktc_article?characterEncoding=UTF8&useSSL=false
    username: root
    password: admin
  jpa:
    properties:
      hibernate:
        format_sql: true                                              # 格式化sql
        show_sql: true                                                # 顯示sql
    database: mysql                                                   # 要操作的目標數據庫類型，默認情況下系統可以自動檢測
    generate-ddl: true                                                # 可以讓SpringDataJPA來生成DDL
    hibernate:
      ddl-auto: update                                                # DDL的策略為update
  redis:
    host: 192.168.1.205
    port: 6379

jwt:
  config:
    key: dfbz                                                         # token秘鑰
    expiration: 60000                                                 # 過期時間，一分鐘
    prefix: dfbz_                                                     # 認證前綴
# 配置Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10101/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}     # 手動設置實例名（默認為微服務名）
  leaseRenewalIntervalInSeconds: 30                                   # 心跳頻率（默認30秒）
  lease-expiration-duration-in-seconds: 90                            # Eureka client發送心跳給server端後，續約到期時間（默認90秒）
