server:
  port: 10101                                   # 指定應用程序的運行端口
spring:
  application:
    name: ktc-eureka                            # 微服務的名稱
eureka:
  client:
    register-with-eureka: false                 # 是否將自己注册到注册中心
    fetch-registry: false                       # 是否从 Eureka 中获取注册信息
    service-url:                                # 配置暴露给 Eureka Client 的请求地址
      defaultZone: http://127.0.0.1:10101/eureka/
  instance:
    enable-self-preservation: false             # 关闭自我保护
    eviction-interval-timer-in-ms: 4000         # 剔除时间间隔，单位：毫秒